//
//  FaqView.swift
//  EnglishCourse
//
//  Created by Roman Maiboroda on 01/03/2024.
//

import SwiftUI
import Combine

struct FaqView: View {
    @State private var isAnimation = false
    @State private var apiKeyText: String = apiKey
    @State private var cancellables: Set<AnyCancellable> = []
    @EnvironmentObject private var coordinator: Coordinator
    
    init() {
        setupPublishers()
    }

    var body: some View {
        ZStack {
            Color.topicsBackground
                .ignoresSafeArea()
            
            VStack {
                Text("Read before using")
                    .font(.title)
                    .fontWeight(.bold)
                    .multilineTextAlignment(.center)
                    .foregroundColor(.white)
                    .shadow(radius: 10)
                    .padding()
    
                Text("This app provides English courses generated by ChatGPT. To use ChatGPT, you need to obtain an API key from your OpenAI Developers console. You can input the API key in this text field or find the variable called apiKey in the code. If you do not enter the API key, the app will work in hardcoded mode, allowing you to test the design of the SwiftUI screens.")
                    .font(.headline)
                    .fontWeight(.bold)
                    .multilineTextAlignment(.center)
                    .foregroundColor(.white)
                    .shadow(radius: 10)
                    .padding([.leading, .trailing])
                TextField(text: $apiKeyText) {
                    Text("API key is empty now")
                }
                .foregroundColor(.white)
                .shadow(radius: 10)
                .font(.headline)
                .padding()
                .overlay(
                        RoundedRectangle(cornerRadius: 40)
                            .stroke(Color.white.opacity(0.5), lineWidth: 5)
                            .shadow(radius: 10)
                    )
                .padding()
            }
        }
        .overlay(
            Button(action: {
                coordinator.dismissSheet()
            }, label: {
                Image(systemName: "xmark")
                    .font(.title)
                    .fontWeight(.bold)
            })
            .padding(.top, 10)
            .padding(.trailing, 16)
            .foregroundColor(.white)
            , alignment: .topTrailing
        )
    }
    
    private func setupPublishers() {
        apiKeyText.publisher
            .sink(receiveCompletion: { completion in
                switch completion {
                case .finished:
                    apiKey = apiKeyText
                case .failure(let error):
                    print(error)
                }
            }, receiveValue: { exercises in
                
            })
            .store(in: &cancellables)
    }
}

#Preview {
    FaqView()
}
